# Generated by Django 4.1.7 on 2023-03-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opening_stock', models.IntegerField(default=0)),
                ('new_stock', models.IntegerField(default=0)),
                ('total_stock', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_sold', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('amount_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_stock', models.IntegerField(default=0)),
            ],
        ),
    ]
