# Generated by Django 4.1.7 on 2023-03-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='mode_of_payment',
            field=models.CharField(choices=[('POS', 'POS'), ('TRANSFER', 'TRANSFER'), ('CASH', 'CASH'), ('DEBT', 'DEBT'), ('COMPLIMENTARY', 'COMPLIMENTARY')], max_length=20),
        ),
    ]
