# Generated by Django 4.1.7 on 2023-03-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='price_per_drink',
            new_name='price',
        ),
    ]
