# Generated by Django 4.1.7 on 2023-03-16 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_alter_sale_mode_of_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complimentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.sale')),
            ],
        ),
    ]
