# Generated by Django 4.1.7 on 2023-03-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_sale_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='cleared_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
