# Generated by Django 4.1.7 on 2023-03-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_alter_sale_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name_plural': 'Drinks'},
        ),
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, default='drink_images/default.png', help_text='Upload a PNG or JPEG image with a maximum size of 1MB', null=True, upload_to='drink_images', verbose_name='Drink Image'),
        ),
    ]
