# Generated by Django 4.1.7 on 2023-03-29 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_debt_cleared_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='closing_stock',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='new_stock',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='opening_stock',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='total_stock',
        ),
        migrations.AddField(
            model_name='drink',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.drink')),
            ],
        ),
        migrations.CreateModel(
            name='ReduceStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reduction', models.PositiveIntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.drink')),
            ],
        ),
    ]
