# Generated by Django 4.1.7 on 2023-03-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0006_alter_drink_options_drink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, default='default=DEFAULT_IMAGE_PATH', help_text='Upload a PNG or JPEG image with a maximum size of 1MB', null=True, upload_to='drink_images', verbose_name='Drink Image'),
        ),
    ]
