# Generated by Django 4.1.7 on 2023-04-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0007_debt_bankused_debt_payment_mode_debt_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bankused',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
