# Generated by Django 4.1.7 on 2023-03-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0008_alter_drink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(default='drinks/default.png', upload_to='drinks'),
        ),
    ]
