# Generated by Django 4.1.7 on 2023-03-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0015_alter_drink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='mode_of_payment',
            field=models.CharField(choices=[('POS', 'POS'), ('TRANSFER', 'TRANSFER'), ('CASH', 'CASH'), ('DEBT', 'DEBT')], max_length=20),
        ),
    ]
