# Generated by Django 4.1.7 on 2023-03-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0016_alter_sale_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='name_or_room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
