# Generated by Django 4.1.7 on 2023-03-06 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0017_sale_name_or_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
