# Generated by Django 4.1.7 on 2023-03-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0018_drink_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='date_created',
        ),
    ]
