# Generated by Django 4.1.7 on 2023-03-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0020_remove_drink_date_drink_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.CharField(choices=[('Soft-drink/Non-alcoholic', 'Soft-drink/Non-alcoholic'), ('Beer', 'Beer'), ('Blended-spirit/Whiskey/Wine', 'Blended-spirit/Whiskey/Wine'), ('Others', 'Others')], default='Others', max_length=100),
        ),
    ]
