# Generated by Django 4.1.7 on 2023-03-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0021_drink_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('name_or_room_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Owing', 'Owing'), ('Cleared', 'Cleared')], default='Owing', max_length=10)),
            ],
        ),
    ]
