# Generated by Django 4.1.7 on 2023-03-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0022_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='name_or_room_number',
            new_name='debtor_name',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='name_or_room_number',
            new_name='debtor_name',
        ),
    ]
