# Generated by Django 4.1.7 on 2023-03-13 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0023_rename_name_or_room_number_debt_debtor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Soft-drink/Non-alcoholic', 'Soft-drink/Non-alcoholic'), ('Beer', 'Beer'), ('Blended-spirit/Whiskey/Wine', 'Blended-spirit/Whiskey/Wine'), ('Others', 'Others')], default='Others', max_length=100)),
                ('image', models.ImageField(blank=True, default='drinks/default.png', null=True, upload_to='drinks')),
                ('opening_stock', models.IntegerField(default=0)),
                ('new_stock', models.IntegerField(default=0)),
                ('total_stock', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_sold', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('amount_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_stock', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_archived', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Archived Drinks',
            },
        ),
        migrations.CreateModel(
            name='DailyDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.IntegerField(default=0)),
                ('new_stock', models.IntegerField(default=0)),
                ('total_stock', models.IntegerField(default=0)),
                ('number_sold', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('closing_stock', models.IntegerField(default=0)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.drink')),
            ],
            options={
                'verbose_name_plural': 'Daily Drinks',
            },
        ),
    ]
