# Generated by Django 4.1.7 on 2023-03-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0024_archiveddrink_dailydrink'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDrinkUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('opening_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('total_stock', models.IntegerField()),
                ('number_sold', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('amount_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_stock', models.IntegerField()),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.drink')),
            ],
            options={
                'verbose_name_plural': 'Daily Drink Updates',
                'unique_together': {('drink', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='DailyDrink',
        ),
    ]
