# Generated by Django 4.1.7 on 2023-03-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0025_dailydrinkupdate_delete_dailydrink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedDrink',
        ),
        migrations.DeleteModel(
            name='DailyDrinkUpdate',
        ),
    ]
