# Generated by Django 4.1.7 on 2023-03-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0027_sale_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
