# Generated by Django 4.1.7 on 2023-03-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0029_sale_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Created_by',
            field=models.CharField(choices=[('CHAIRMAN', 'CHAIRMAN'), ('MANAGER', 'MANAGER'), ('STAFF', 'STAFF'), ('CUSTOMER', 'CUSTOMER')], default='STAFF', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_by',
            field=models.CharField(choices=[('CHAIRMAN', 'CHAIRMAN'), ('MANAGER', 'MANAGER'), ('STAFF', 'STAFF'), ('CUSTOMER', 'CUSTOMER')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
