# Generated by Django 4.1.7 on 2023-03-15 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_management', '0030_sale_created_by_sale_discount_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='Created_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='discount_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='discount_reason',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='reason_for_discount',
            field=models.CharField(blank=True, choices=[('CHAIRMAN', 'CHAIRMAN'), ('MANAGER', 'MANAGER'), ('STAFF', 'STAFF'), ('CUSTOMER', 'CUSTOMER')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
